// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { HelloApiV1HelloGetData, HelloApiV1HelloGetResponses, MockSseStreamApiV1AiChatMockGetData, MockSseStreamApiV1AiChatMockGetResponses, StreamChatApiV1AiChatStreamPostData, StreamChatApiV1AiChatStreamPostResponses, StreamChatApiV1AiChatStreamPostErrors, ListSessionsApiV1AiChatSessionsGetData, ListSessionsApiV1AiChatSessionsGetResponses, GetSessionApiV1AiChatSessionsSessionIdGetData, GetSessionApiV1AiChatSessionsSessionIdGetResponses, GetSessionApiV1AiChatSessionsSessionIdGetErrors, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Hello
 */
export const helloApiV1HelloGet = <ThrowOnError extends boolean = false>(options?: Options<HelloApiV1HelloGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HelloApiV1HelloGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/hello/',
        ...options
    });
};

/**
 * Mock Sse Stream
 */
export const mockSseStreamApiV1AiChatMockGet = <ThrowOnError extends boolean = false>(options?: Options<MockSseStreamApiV1AiChatMockGetData, ThrowOnError>) => {
    return (options?.client ?? client).sse.get<MockSseStreamApiV1AiChatMockGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/ai-chat/mock',
        ...options
    });
};

/**
 * Stream Chat
 */
export const streamChatApiV1AiChatStreamPost = <ThrowOnError extends boolean = false>(options: Options<StreamChatApiV1AiChatStreamPostData, ThrowOnError>) => {
    return (options.client ?? client).sse.post<StreamChatApiV1AiChatStreamPostResponses, StreamChatApiV1AiChatStreamPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/ai-chat/stream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List Sessions
 */
export const listSessionsApiV1AiChatSessionsGet = <ThrowOnError extends boolean = false>(options?: Options<ListSessionsApiV1AiChatSessionsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSessionsApiV1AiChatSessionsGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/ai-chat/sessions',
        ...options
    });
};

/**
 * Get Session
 */
export const getSessionApiV1AiChatSessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSessionApiV1AiChatSessionsSessionIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSessionApiV1AiChatSessionsSessionIdGetResponses, GetSessionApiV1AiChatSessionsSessionIdGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/ai-chat/sessions/{session_id}',
        ...options
    });
};

/**
 * Login
 * Issue JWT token after validating credentials.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
        url: '/api/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Me
 * Get current verified user.
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<MeApiV1AuthMeGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me',
        ...options
    });
};
