// This file is auto-generated by @hey-api/openapi-ts

/**
 * AIChatRequest
 */
export type AiChatRequest = {
    /**
     * Message
     */
    message?: string;
    /**
     * Session Id
     */
    session_id?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HelloResponse
 */
export type HelloResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HelloApiV1HelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hello/';
};

export type HelloApiV1HelloGetResponses = {
    /**
     * Successful Response
     */
    200: HelloResponse;
};

export type HelloApiV1HelloGetResponse = HelloApiV1HelloGetResponses[keyof HelloApiV1HelloGetResponses];

export type MockSseStreamApiV1AiChatMockGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai-chat/mock';
};

export type MockSseStreamApiV1AiChatMockGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamChatApiV1AiChatStreamPostData = {
    body: AiChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai-chat/stream';
};

export type StreamChatApiV1AiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatApiV1AiChatStreamPostError = StreamChatApiV1AiChatStreamPostErrors[keyof StreamChatApiV1AiChatStreamPostErrors];

export type StreamChatApiV1AiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
