[program:__SERVICE_NAME__]
directory=__APP_DIR__
command=__COMMAND__
user=__RUN_USER__
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=__APP_DIR__/logs/backend.stdout.log
stderr_logfile=__APP_DIR__/logs/backend.stderr.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
environment=PYTHONUNBUFFERED="1"
